### ISSUE TITLE
Reactでサイドバーを実装する方法を調べる

### ISSUE THREAD

**Issue by takatoshiinaoka** [kazut2000/google-map#4]
@kazut2000 
参考にしたサイトのURLや実装方法のメモをこのIssueにまとめてください

**Comment by kazut2000** [comment]
https://mebee.info/2020/03/21/post-7501/

**Comment by takatoshiinaoka** [comment]
これで実装できた
https://qiita.com/uniuni__8282/items/359a5ec90742a696a1c1
